print ("________________________________________________")
name= input("Enter your name: ")
age= int(input( "enter your age: "))
address= input("enter your address: ")
print ("________________________________________________")
print ("\nUser Information:")
print ("________________________________________________")
print (" ")
print( f"Name: {name}")
print( f"Age: {age}")
print( f"Address: {address}")
print ("________________________________________________")
